// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function shirtSizeOfString(str) {
  switch (str) {
    case "L" :
        return /* Large */2;
    case "M" :
        return /* Medium */1;
    case "S" :
        return /* Small */0;
    case "XL" :
        return /* XLarge */3;
    default:
      return ;
  }
}

function price(size) {
  switch (size) {
    case /* Small */0 :
        return 11.00;
    case /* Medium */1 :
        return 12.50;
    case /* Large */2 :
        return 14.00;
    case /* XLarge */3 :
        return 16.00;
    
  }
}

exports.shirtSizeOfString = shirtSizeOfString;
exports.price = price;
/* No side effect */
