// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

var calcButton = document.getElementById("calculate");

function calculate(param) {
  console.log("You clicked me!");
  
}

if (calcButton == null) {
  console.log("None");
} else {
  calcButton.addEventListener("click", calculate);
}

var D;

var Doc;

var Elem;

var calcButton$1 = (calcButton == null) ? undefined : Caml_option.some(calcButton);

exports.D = D;
exports.Doc = Doc;
exports.Elem = Elem;
exports.calcButton = calcButton$1;
exports.calculate = calculate;
/* calcButton Not a pure module */
