// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var ShirtSize$Chapter4 = require("./ShirtSize.bs.js");

function calculate(param) {
  console.log("You clicked me!");
  var getValue = function (element) {
    var __x = Belt_Option.map(element, (function (prim) {
            return prim;
          }));
    return Belt_Option.map(__x, (function (prim) {
                  return prim.value;
                }));
  };
  var toInt = function (str) {
    var result;
    try {
      result = Caml_format.caml_int_of_string(str);
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.RE_EXN_ID === "Failure") {
        if (exn._1 === "int_of_string") {
          return ;
        }
        throw exn;
      }
      throw exn;
    }
    return result;
  };
  var quantity = Belt_Option.flatMap(getValue(Caml_option.nullable_to_opt(document.getElementById("quantity"))), toInt);
  var __x = getValue(Caml_option.nullable_to_opt(document.getElementById("size")));
  var __x$1 = Belt_Option.flatMap(__x, ShirtSize$Chapter4.shirtSizeOfString);
  var unitPrice = Belt_Option.map(__x$1, ShirtSize$Chapter4.price);
  var totalPrice = unitPrice !== undefined && quantity !== undefined ? unitPrice * quantity : undefined;
  var priceString = totalPrice !== undefined ? totalPrice.toFixed(2) : "";
  var __x$2 = document.getElementById("price");
  Belt_Option.map((__x$2 == null) ? undefined : Caml_option.some(__x$2), (function (__x) {
          __x.innerText = priceString;
          
        }));
  
}

var calcButton = document.getElementById("calculate");

if (calcButton == null) {
  console.log("None");
} else {
  calcButton.addEventListener("click", calculate);
}

var D;

var Doc;

var Elem;

var calcButton$1 = (calcButton == null) ? undefined : Caml_option.some(calcButton);

exports.D = D;
exports.Doc = Doc;
exports.Elem = Elem;
exports.calculate = calculate;
exports.calcButton = calcButton$1;
/* calcButton Not a pure module */
