// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

console.log("Hello, BuckleScript and Reason!");

var arr = [
  1,
  2,
  3,
  4,
  5
];

function forEachArr(cb, _array) {
  while(true) {
    var array = _array;
    if (array.length === 0) {
      return ;
    }
    if (array.length !== 0) {
      Curry._1(cb, Caml_array.get(array, 0));
      _array = Belt_Array.slice(array, 1, array.length - 1 | 0);
      continue ;
    }
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Demo.re",
            4,
            63
          ],
          Error: new Error()
        };
  };
}

console.log(forEachArr((function (prim) {
            console.log(prim);
            
          }), arr));

exports.arr = arr;
exports.forEachArr = forEachArr;
/*  Not a pure module */
