// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function sumUntilNegative(_items, _total) {
  while(true) {
    var total = _total;
    var items = _items;
    if (!items) {
      return total;
    }
    var x = items.hd;
    if (x < 0) {
      return total;
    }
    _total = total + x | 0;
    _items = items.tl;
    continue ;
  };
}

exports.sumUntilNegative = sumUntilNegative;
/* No side effect */
