// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var DisplayList$Chapter6 = require("./DisplayList.bs.js");

function takeWhile(predicate, list) {
  var _accumulator = /* [] */0;
  var _list = list;
  while(true) {
    var list$1 = _list;
    var accumulator = _accumulator;
    if (!list$1) {
      return accumulator;
    }
    var x = list$1.hd;
    if (Curry._1(predicate, x)) {
      _list = list$1.tl;
      _accumulator = Belt_List.concat(accumulator, {
            hd: x,
            tl: /* [] */0
          });
      continue ;
    }
    if (!Curry._1(predicate, x)) {
      return accumulator;
    }
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "YourTurn.re",
            19,
            72
          ],
          Error: new Error()
        };
  };
}

function dropWhile(predicate, _list) {
  while(true) {
    var list = _list;
    if (!list) {
      return list;
    }
    var xs = list.tl;
    var x = list.hd;
    if (Curry._1(predicate, x)) {
      _list = xs;
      continue ;
    }
    if (!Curry._1(predicate, x)) {
      return Pervasives.$at({
                  hd: x,
                  tl: /* [] */0
                }, xs);
    }
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "YourTurn.re",
            32,
            23
          ],
          Error: new Error()
        };
  };
}

var data = {
  hd: 2,
  tl: {
    hd: 6,
    tl: {
      hd: 42,
      tl: {
        hd: 5,
        tl: {
          hd: 7,
          tl: {
            hd: 20,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }
      }
    }
  }
};

function isEven(n) {
  return n % 2 === 0;
}

var __x = takeWhile(isEven, data);

console.log(DisplayList$Chapter6.stringOfList(__x, (function (prim) {
            return String(prim);
          })));

var __x$1 = dropWhile(isEven, data);

console.log(DisplayList$Chapter6.stringOfList(__x$1, (function (prim) {
            return String(prim);
          })));

exports.takeWhile = takeWhile;
exports.dropWhile = dropWhile;
exports.data = data;
exports.isEven = isEven;
/*  Not a pure module */
