// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function distance(p0, p1) {
  return Math.sqrt(Math.pow(p0[0] - p1[0], 2.0) + Math.pow(p0[1] - p1[1], 2.0));
}

var startPoint = [
  3.5,
  4.6
];

var endPoint = [
  0.5,
  9.6
];

var result = distance(startPoint, endPoint);

console.log(result);

exports.distance = distance;
exports.startPoint = startPoint;
exports.endPoint = endPoint;
exports.result = result;
/* result Not a pure module */
