// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ShirtSize$Chapter5 = require("./ShirtSize.bs.js");

var myShirt = /* XLarge */{
  _0: 1
};

var myPrice = ShirtSize$Chapter5.price(myShirt);

console.log(ShirtSize$Chapter5.toFixed(myPrice, 2));

exports.myShirt = myShirt;
exports.myPrice = myPrice;
/* myPrice Not a pure module */
