// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ShirtSize$Chapter5 = require("./ShirtSize.bs.js");

var order1 = [
  3,
  /* Medium */1
];

var order2 = [
  5,
  /* XLarge */{
    _0: 3
  }
];

function toString(param) {
  return String(param[0]) + (" " + ShirtSize$Chapter5.toString(param[1]));
}

console.log(toString(order1));

console.log(toString(order2));

exports.order1 = order1;
exports.order2 = order2;
exports.toString = toString;
/*  Not a pure module */
