// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function price(size) {
  if (typeof size !== "number") {
    return 16.00 + (size._0 - 1 | 0) * 0.50;
  }
  switch (size) {
    case /* Small */0 :
        return 11.00;
    case /* Medium */1 :
        return 12.50;
    case /* Large */2 :
        return 14.00;
    
  }
}

function toString(size) {
  if (typeof size !== "number") {
    return $$String.make(size._0, /* "X" */88) + "L";
  }
  switch (size) {
    case /* Small */0 :
        return "S";
    case /* Medium */1 :
        return "M";
    case /* Large */2 :
        return "L";
    
  }
}

function fromString(str) {
  switch (str) {
    case "L" :
        return /* Large */2;
    case "M" :
        return /* Medium */1;
    case "S" :
        return /* Small */0;
    case "XL" :
        return /* XLarge */{
                _0: 1
              };
    case "XXL" :
        return /* XLarge */{
                _0: 2
              };
    case "XXXL" :
        return /* XLarge */{
                _0: 3
              };
    case "XXXXL" :
        return /* XLarge */{
                _0: 4
              };
    default:
      return ;
  }
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

exports.price = price;
exports.toString = toString;
exports.fromString = fromString;
exports.toFixed = toFixed;
/* No side effect */
