/***
 * Excerpted from "Web Development with ReasonML",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material,
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose.
 * Visit http://www.pragmaticprogrammer.com/titles/reasonml for more book information.
***/
// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';


console.log("Size is", /* Medium */1);

var mySize = /* Medium */1;

exports.mySize = mySize;
/*  Not a pure module */
