// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

var jsonStr = Json.parse("\"two worlds\"");

var decodedStr = jsonStr !== undefined ? Json_decode.string(Caml_option.valFromOption(jsonStr)) : "";

console.log(decodedStr);

function floatArrayDecoder(param) {
  return Json_decode.array(Json_decode.$$float, param);
}

var decodedArray = Belt_Option.mapWithDefault(Json.parse("[3,4,5,6,7,8]"), [], floatArrayDecoder);

console.log(decodedArray);

var jsonObj = Json.parse("{\"size\": \"XXL\", \"qty\": 10}");

var decodedObj = jsonObj !== undefined ? Json_decode.field("qty", Json_decode.$$int, Caml_option.valFromOption(jsonObj)) : 0;

console.log(decodedObj);

var objStats = "{\"title\": \"color\", \"choices\": [\"White\", \"Blue\", \"Red\", \"Green\", \"Brown\"], \"totals\":[118, 114, 73, 67, 28]}";

var jsonObj$1 = Json.parse(objStats);

var colorStats;

if (jsonObj$1 !== undefined) {
  var jsonObj$2 = Caml_option.valFromOption(jsonObj$1);
  colorStats = {
    title: Json_decode.field("title", Json_decode.string, jsonObj$2),
    choices: Json_decode.field("choices", (function (param) {
            return Json_decode.array(Json_decode.string, param);
          }), jsonObj$2),
    totals: Json_decode.field("totals", (function (param) {
            return Json_decode.array(Json_decode.$$int, param);
          }), jsonObj$2)
  };
} else {
  colorStats = {
    title: "",
    choices: [],
    totals: []
  };
}

var sleeveStats_choices = [
  "short sleeve",
  "long sleeve",
  "extra-long sleeve"
];

var sleeveStats_totals = [
  129,
  217,
  54
];

var sleeveStats = {
  title: "sleeve",
  choices: sleeveStats_choices,
  totals: sleeveStats_totals
};

var sleeveJson = Json_encode.object_({
      hd: [
        "title",
        "sleeve"
      ],
      tl: {
        hd: [
          "choices",
          sleeveStats_choices
        ],
        tl: {
          hd: [
            "totals",
            Json_encode.array((function (prim) {
                    return prim;
                  }), sleeveStats_totals)
          ],
          tl: /* [] */0
        }
      }
    });

console.log(Json.stringify(sleeveJson));

var D;

var E;

exports.D = D;
exports.decodedStr = decodedStr;
exports.floatArrayDecoder = floatArrayDecoder;
exports.decodedArray = decodedArray;
exports.decodedObj = decodedObj;
exports.objStats = objStats;
exports.colorStats = colorStats;
exports.sleeveStats = sleeveStats;
exports.E = E;
exports.sleeveJson = sleeveJson;
/* jsonStr Not a pure module */
