// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var age = {
  contents: 22
};

function birthday(a) {
  a.contents = a.contents + 1 | 0;
  
}

birthday(age);

console.log(age.contents);

console.log(age.contents);

exports.age = age;
exports.birthday = birthday;
/*  Not a pure module */
