// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Author = {};

var Book = {
  Author: Author
};

console.log("Stephenson");

var b = {
  title: "Anathem",
  author: {
    firstName: "Neal",
    lastName: "Stephenson"
  },
  isbn13: "978-0-06-147409-5"
};

exports.Book = Book;
exports.b = b;
/*  Not a pure module */
