// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function happyBirthday(someone) {
  someone.age = someone.age + 1 | 0;
  
}

var friend = {
  name: "Juanita Fulano",
  age: 34
};

happyBirthday(friend);

console.log(friend.age);

exports.happyBirthday = happyBirthday;
exports.friend = friend;
/*  Not a pure module */
