// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function calcPercent(score, max) {
  return /* Percent */{
          _0: score._0 / max._0 * 100.0
        };
}

exports.calcPercent = calcPercent;
/* No side effect */
